AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Deployment stage for a website using Netlify CMS.

Parameters:
  FullDomain:
    Type: String
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
  GitHostname:
    Type: String
    Default: https://github.com
  OAuthProvider:
    Type: String
    Default: github
  OAuthScopes:
    Type: String
    Default: user,repo
  OAuthAuthorizePath:
    Type: String
    Default: /login/oauth/authorize
  OAuthTokenPath:
    Type: String
    Default: /login/oauth/access_token
  NetlifyStackName:
    Type: String
    Description: Name of the stack exporting a Rest API ID for a self-hosted Netlify CMS.
    Default: NetlifyCMSAuth

Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Fn::ImportValue: !Sub '${NetlifyStackName}-RestApiId'
      StageName: !Ref AWS::StackName
      StageDescription:
        ThrottlingRateLimit: 100
        ThrottlingBurstLimit: 50
        LoggingLevel: ERROR
        Variables:
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
          DOMAIN: !Ref FullDomain
          GIT_HOSTNAME: !Ref GitHostname
          OAUTH_AUTHORIZE_PATH: !Ref OAuthAuthorizePath
          OAUTH_PROVIDER: !Ref OAuthProvider
          OAUTH_SCOPES: !Ref OAuthScopes
          OAUTH_TOKEN_PATH: !Ref OAuthTokenPath
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: arn:aws:acm:us-east-1:694316186841:certificate/b45b3e52-a6bb-4dec-9dc2-994ad5fc7b78 # TODO import
      DomainName: api.seniorinfluence.com # TODO make variable
      EndpointConfiguration:
        - EDGE
      SecurityPolicy: TLS_1_2
  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      RestApiId:
        Fn::ImportValue: !Sub '${NetlifyStackName}-RestApiId'
      DomainName: !Ref DomainName
      Stage: !Ref AWS::StackName
      BasePath: admin
