AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Deployment stage for a website using Netlify CMS.

Parameters:
  Domain:
    Type: String
    Description: Domain of website using Netlify CMS.
  ClientId:
    Type: String
    Description: Client ID for Netlify CMS authentication.
    NoEcho: true
  ClientSecret:
    Type: String
    Description: Client secret for Netlify CMS authentication.
    NoEcho: true
  GitHostname:
    Type: String
    Default: https://github.com
  OAuthProvider:
    Type: String
    Default: github
  OAuthScopes:
    Type: String
    Default: user,repo
  OAuthAuthorizePath:
    Type: String
    Default: /login/oauth/authorize
  OAuthTokenPath:
    Type: String
    Default: /login/oauth/access_token
  NetlifyCMSStackName:
    Type: String
    Default: NetlifyCMSAuth

Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Fn::ImportValue: !Sub '${NetlifyCMSStackName}-RestApiId'
      StageName: TestStage
      StageDescription:
        ThrottlingRateLimit: 100
        ThrottlingBurstLimit: 50
        Variables:
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
          DOMAIN: !Ref Domain
          GIT_HOSTNAME: !Ref GitHostname
          OAUTH_AUTHORIZE_PATH: !Ref OAuthAuthorizePath
          OAUTH_PROVIDER: !Ref OAuthProvider
          OAUTH_SCOPES: !Ref OAuthScopes
          OAUTH_TOKEN_PATH: !Ref OAuthTokenPath

  # CustomDomain:
  #   Type: AWS::ApiGateway::DomainName
  #   Properties:
  #     CertificateArn: arn:aws:acm:us-east-1:694316186841:certificate/b45b3e52-a6bb-4dec-9dc2-994ad5fc7b78
  #     DomainName: api.seniorinfluence.com
  #     SecurityPolicy: TLS_1_2
  #     EndpointConfiguration:
  #       - EDGE
  #
  # PathMapping:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     RestApiId:
  #       Fn::ImportValue: !Sub '${NetlifyCMSStackName}-RestApiId'
  #     DomainName: !Ref CustomDomain
  #     Stage: TestStage # Better way to do this?
  #     BasePath: admin
